### PR TITLE
Chore/eslint prettier

### PR DESCRIPTION
**Pull request by br-Chan**
Set up ESLint and Prettier, and ran both.

The current Prettier formatting:
- tab indents are 2 spaces
- no single quotes (i.e.` "its a me mario"` and not `'its a me luigi'`)
- trailing commas
- Tailwind CSS gets formatted too

Will edit the readme to document how to easily run these.

### CODE REVIEW

**Comment by Hoverth** [comment]
Looks good to me!

**Review by Hoverth — APPROVED** [review]

**Comment by br-Chan** [comment]
> !

Hell yeah baby

How are we doing merges? Does someone else have to do it or am I free to do it myself?

**Comment by Hoverth** [comment]
Yeah we can self-merge

**Review by harbassan — APPROVED** [review]
lgtm

**Pull request merged**
